name: "Docker Build Web"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the Docker image"
        required: false
        default: "latest"
        type: string

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Depot CLI
        uses: depot/setup-action@v1

      - name: Create .env file
        run: |
          echo "WEB_URL=http://localhost:3000" > .env
          echo "NEXT_PUBLIC_DOCKER_BUILD=true" >> .env

      - name: Build and save multi-arch image to Depot Registry
        uses: depot/build-push-action@v1
        with:
          project: 1hppsd1861
          context: .
          file: apps/web/Dockerfile
          platforms: linux/amd64,linux/arm64
          save: true
          save-tags: |
            cap-web-latest
            cap-web-${{ inputs.tag || 'latest' }}
            cap-web-${{ github.sha }}
