name: "Docker Build Media Server"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the Docker image"
        required: false
        default: "latest"
        type: string
  push:
    branches:
      - main
    paths:
      - "apps/media-server/**"

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Depot CLI
        uses: depot/setup-action@v1

      - name: Build and save multi-arch image to Depot Registry
        uses: depot/build-push-action@v1
        with:
          project: 1hppsd1861
          context: ./apps/media-server
          file: ./apps/media-server/Dockerfile.standalone
          platforms: linux/amd64,linux/arm64
          save: true
          save-tags: |
            cap-media-server-latest
            cap-media-server-${{ inputs.tag || 'latest' }}
            cap-media-server-${{ github.sha }}
